/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAiAssistantRouteImport } from './routes/_app/ai-assistant'
import { Route as AppAiTaskPlannerRouteImport } from './routes/_app/ai-task-planner'
import { Route as AppAutomationRouteImport } from './routes/_app/automation'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEmailAssistantRouteImport } from './routes/_app/email-assistant'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppMeetingSummarizerRouteImport } from './routes/_app/meeting-summarizer'
import { Route as AppProcessImprovementRouteImport } from './routes/_app/process-improvement'
import { Route as AppProductionRouteImport } from './routes/_app/production'
import { Route as AppQualityRouteImport } from './routes/_app/quality'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppResearchAssistantRouteImport } from './routes/_app/research-assistant'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTaskPlannerRoute = AppAiTaskPlannerRouteImport.update({
  id: '/ai-task-planner',
  path: '/ai-task-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailAssistantRoute = AppEmailAssistantRouteImport.update({
  id: '/email-assistant',
  path: '/email-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingSummarizerRoute = AppMeetingSummarizerRouteImport.update({
  id: '/meeting-summarizer',
  path: '/meeting-summarizer',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessImprovementRoute = AppProcessImprovementRouteImport.update({
  id: '/process-improvement',
  path: '/process-improvement',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchAssistantRoute = AppResearchAssistantRouteImport.update({
  id: '/research-assistant',
  path: '/research-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/ai-task-planner': typeof AppAiTaskPlannerRoute
  '/automation': typeof AppAutomationRoute
  '/dashboard': typeof AppDashboardRoute
  '/email-assistant': typeof AppEmailAssistantRoute
  '/inventory': typeof AppInventoryRoute
  '/meeting-summarizer': typeof AppMeetingSummarizerRoute
  '/process-improvement': typeof AppProcessImprovementRoute
  '/production': typeof AppProductionRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/research-assistant': typeof AppResearchAssistantRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/ai-task-planner': typeof AppAiTaskPlannerRoute
  '/automation': typeof AppAutomationRoute
  '/dashboard': typeof AppDashboardRoute
  '/email-assistant': typeof AppEmailAssistantRoute
  '/inventory': typeof AppInventoryRoute
  '/meeting-summarizer': typeof AppMeetingSummarizerRoute
  '/process-improvement': typeof AppProcessImprovementRoute
  '/production': typeof AppProductionRoute
  '/quality': typeof AppQualityRoute
  '/reports': typeof AppReportsRoute
  '/research-assistant': typeof AppResearchAssistantRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/ai-task-planner': typeof AppAiTaskPlannerRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/email-assistant': typeof AppEmailAssistantRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/meeting-summarizer': typeof AppMeetingSummarizerRoute
  '/_app/process-improvement': typeof AppProcessImprovementRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/quality': typeof AppQualityRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/research-assistant': typeof AppResearchAssistantRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/ai-task-planner'
    | '/automation'
    | '/dashboard'
    | '/email-assistant'
    | '/inventory'
    | '/meeting-summarizer'
    | '/process-improvement'
    | '/production'
    | '/quality'
    | '/reports'
    | '/research-assistant'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/ai-task-planner'
    | '/automation'
    | '/dashboard'
    | '/email-assistant'
    | '/inventory'
    | '/meeting-summarizer'
    | '/process-improvement'
    | '/production'
    | '/quality'
    | '/reports'
    | '/research-assistant'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-assistant'
    | '/_app/ai-task-planner'
    | '/_app/automation'
    | '/_app/dashboard'
    | '/_app/email-assistant'
    | '/_app/inventory'
    | '/_app/meeting-summarizer'
    | '/_app/process-improvement'
    | '/_app/production'
    | '/_app/quality'
    | '/_app/reports'
    | '/_app/research-assistant'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-task-planner': {
      id: '/_app/ai-task-planner'
      path: '/ai-task-planner'
      fullPath: '/ai-task-planner'
      preLoaderRoute: typeof AppAiTaskPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-assistant': {
      id: '/_app/email-assistant'
      path: '/email-assistant'
      fullPath: '/email-assistant'
      preLoaderRoute: typeof AppEmailAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meeting-summarizer': {
      id: '/_app/meeting-summarizer'
      path: '/meeting-summarizer'
      fullPath: '/meeting-summarizer'
      preLoaderRoute: typeof AppMeetingSummarizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/process-improvement': {
      id: '/_app/process-improvement'
      path: '/process-improvement'
      fullPath: '/process-improvement'
      preLoaderRoute: typeof AppProcessImprovementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research-assistant': {
      id: '/_app/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof AppResearchAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAiTaskPlannerRoute: typeof AppAiTaskPlannerRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailAssistantRoute: typeof AppEmailAssistantRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMeetingSummarizerRoute: typeof AppMeetingSummarizerRoute
  AppProcessImprovementRoute: typeof AppProcessImprovementRoute
  AppProductionRoute: typeof AppProductionRoute
  AppQualityRoute: typeof AppQualityRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResearchAssistantRoute: typeof AppResearchAssistantRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAiTaskPlannerRoute: AppAiTaskPlannerRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmailAssistantRoute: AppEmailAssistantRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMeetingSummarizerRoute: AppMeetingSummarizerRoute,
  AppProcessImprovementRoute: AppProcessImprovementRoute,
  AppProductionRoute: AppProductionRoute,
  AppQualityRoute: AppQualityRoute,
  AppReportsRoute: AppReportsRoute,
  AppResearchAssistantRoute: AppResearchAssistantRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
