/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAiTaskPlannerRouteImport } from './routes/_app/ai-task-planner'
import { Route as AppAutomationRouteImport } from './routes/_app/automation'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppProcessImprovementRouteImport } from './routes/_app/process-improvement'
import { Route as AppProductionRouteImport } from './routes/_app/production'
import { Route as AppQualityRouteImport } from './routes/_app/quality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiTaskPlannerRoute = AppAiTaskPlannerRouteImport.update({
  id: '/ai-task-planner',
  path: '/ai-task-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationRoute = AppAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessImprovementRoute = AppProcessImprovementRouteImport.update({
  id: '/process-improvement',
  path: '/process-improvement',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-task-planner': typeof AppAiTaskPlannerRoute
  '/automation': typeof AppAutomationRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/process-improvement': typeof AppProcessImprovementRoute
  '/production': typeof AppProductionRoute
  '/quality': typeof AppQualityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-task-planner': typeof AppAiTaskPlannerRoute
  '/automation': typeof AppAutomationRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/process-improvement': typeof AppProcessImprovementRoute
  '/production': typeof AppProductionRoute
  '/quality': typeof AppQualityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-task-planner': typeof AppAiTaskPlannerRoute
  '/_app/automation': typeof AppAutomationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/process-improvement': typeof AppProcessImprovementRoute
  '/_app/production': typeof AppProductionRoute
  '/_app/quality': typeof AppQualityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-task-planner'
    | '/automation'
    | '/dashboard'
    | '/inventory'
    | '/process-improvement'
    | '/production'
    | '/quality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-task-planner'
    | '/automation'
    | '/dashboard'
    | '/inventory'
    | '/process-improvement'
    | '/production'
    | '/quality'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-task-planner'
    | '/_app/automation'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/process-improvement'
    | '/_app/production'
    | '/_app/quality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-task-planner': {
      id: '/_app/ai-task-planner'
      path: '/ai-task-planner'
      fullPath: '/ai-task-planner'
      preLoaderRoute: typeof AppAiTaskPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation': {
      id: '/_app/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AppAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/process-improvement': {
      id: '/_app/process-improvement'
      path: '/process-improvement'
      fullPath: '/process-improvement'
      preLoaderRoute: typeof AppProcessImprovementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production': {
      id: '/_app/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiTaskPlannerRoute: typeof AppAiTaskPlannerRoute
  AppAutomationRoute: typeof AppAutomationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppProcessImprovementRoute: typeof AppProcessImprovementRoute
  AppProductionRoute: typeof AppProductionRoute
  AppQualityRoute: typeof AppQualityRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiTaskPlannerRoute: AppAiTaskPlannerRoute,
  AppAutomationRoute: AppAutomationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppProcessImprovementRoute: AppProcessImprovementRoute,
  AppProductionRoute: AppProductionRoute,
  AppQualityRoute: AppQualityRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
